apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase-ws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbase-ws
  template:
    metadata:
      labels:
        app: coinbase-ws
    spec:
      containers:
      - name: coinbase-ws
        image: coinbase-websocket:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: coinbase-secrets
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m" 