apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- secrets.yaml

namePrefix: dev-

images:
- name: coinbase-data-ingestion-service
  newName: 192.168.1.221:5001/coinbase-data-ingestion-service
  newTag: latest

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    kind: Deployment
    name: coinbase-ws
- patch: |-
    - op: replace
      path: /metadata/name
      value: coinbase-secrets
  target:
    kind: Secret
    name: coinbase-secrets