name: K8s Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up k3d
      run: |
        wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        k3d cluster create test-cluster
    
    - name: Run development environment
      run: |
        chmod +x utils/k8s_dev.sh
        ./utils/k8s_dev.sh &
        sleep 30  # Wait for deployment
    
    - name: Run tests
      run: |
        chmod +x utils/k8s_test.sh
        ./utils/k8s_test.sh

    - name: Clean up
      if: always()
      run: k3d cluster delete test-cluster

  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to staging
      run: |
        kubectl apply -k k8s/overlays/staging 